# Answers what were given during boilerplate initialization
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: 56ddfef
_src_path: https://github.com/saritasa-nest/saritasa-python-boilerplate-open-source.git
folder_name: saritasa_invocations
min_python_version: 3.1
package_description: Collection of invoke commands used by Saritasa
package_name: saritasa-invocations
